# Generated by Django 5.1.2 on 2026-03-12 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarminCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garmin_username', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_garmin_password', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
