# Generated by Django 5.1.2 on 2026-03-12 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('distance', models.IntegerField()),
                ('avg_heart_rate', models.IntegerField()),
                ('low_heart_rate', models.IntegerField()),
                ('high_heart_rate', models.IntegerField()),
                ('time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiftingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('weight', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RunningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('distance', models.IntegerField()),
                ('avg_heart_rate', models.IntegerField()),
                ('low_heart_rate', models.IntegerField()),
                ('high_heart_rate', models.IntegerField()),
                ('time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwimmingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('distance', models.IntegerField()),
                ('avg_heart_rate', models.IntegerField()),
                ('low_heart_rate', models.IntegerField()),
                ('high_heart_rate', models.IntegerField()),
                ('time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GarminUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('VO2_max', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('active_minutes', models.IntegerField()),
                ('activty_type', models.CharField(max_length=255)),
                ('activty_amount', models.IntegerField()),
                ('cycling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garmin_bot.cyclingstats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lifting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garmin_bot.liftingstats')),
                ('running', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garmin_bot.runningstats')),
                ('swimming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garmin_bot.swimmingstats')),
            ],
        ),
    ]
