# Generated by Django 5.1.2 on 2026-03-12 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclingstats',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='garminuserdata',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='liftingstats',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='runningstats',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='swimmingstats',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
