# Generated by Django 5.1.2 on 2026-03-24 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin_bot', '0002_alter_cyclingstats_date_recorded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=64)),
                ('activity_name', models.CharField(blank=True, default='', max_length=255)),
                ('activity_type', models.CharField(blank=True, default='', max_length=100)),
                ('start_time_local', models.DateTimeField(blank=True, null=True)),
                ('distance_meters', models.FloatField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('calories', models.FloatField(default=0)),
                ('payload', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time_local', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_id'), name='uniq_user_activity_id')],
            },
        ),
    ]
