# Generated by Django 5.1.2 on 2026-03-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin_bot', '0003_garminactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='garminuserdata',
            name='aggregation_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='garminuserdata',
            name='range_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garminuserdata',
            name='range_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
