# Generated by Django 5.1.2 on 2026-03-18 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarminWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garmin_workout_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at_garmin', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workout_plans.workoutplan')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_plans.garminworkout')),
            ],
        ),
        migrations.AddConstraint(
            model_name='garminworkout',
            constraint=models.UniqueConstraint(fields=('user', 'garmin_workout_id'), name='uniq_user_garmin_workout_id'),
        ),
        migrations.AddConstraint(
            model_name='workoutplanday',
            constraint=models.UniqueConstraint(fields=('plan', 'day'), name='uniq_plan_day'),
        ),
    ]
