# Generated by Django 5.1.2 on 2026-03-25

from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_day_to_items(apps, schema_editor):
    WorkoutPlanDay = apps.get_model("workout_plans", "WorkoutPlanDay")
    WorkoutPlanItem = apps.get_model("workout_plans", "WorkoutPlanItem")

    for day in WorkoutPlanDay.objects.all().iterator():
        workout_id = getattr(day, "workout_id", None)
        cardio_activity = getattr(day, "cardio_activity", "") or ""
        completed = bool(getattr(day, "completed", False))

        if workout_id or cardio_activity:
            WorkoutPlanItem.objects.create(
                day_id=day.id,
                position=0,
                workout_id=workout_id,
                cardio_activity=cardio_activity,
                notes="",
                completed=completed,
            )


def backwards_copy_items_to_day(apps, schema_editor):
    WorkoutPlanDay = apps.get_model("workout_plans", "WorkoutPlanDay")
    WorkoutPlanItem = apps.get_model("workout_plans", "WorkoutPlanItem")

    # Best-effort rollback: set the first item as the day's workout/cardio/completed.
    for day in WorkoutPlanDay.objects.all().iterator():
        first_item = (
            WorkoutPlanItem.objects.filter(day_id=day.id).order_by("position", "id").first()
        )
        if not first_item:
            continue
        day.workout_id = first_item.workout_id
        day.cardio_activity = first_item.cardio_activity or ""
        day.completed = bool(first_item.completed)
        day.save(update_fields=["workout", "cardio_activity", "completed"])


class Migration(migrations.Migration):
    dependencies = [
        ("workout_plans", "0003_workoutplan_activation_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutPlanItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0)),
                ("cardio_activity", models.CharField(blank=True, choices=[("running", "Running"), ("cycling", "Cycling"), ("swimming", "Swimming"), ("walking", "Walking"), ("rowing", "Rowing"), ("rest", "Rest day")], default="", max_length=20)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("completed", models.BooleanField(default=False)),
                ("day", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="workout_plans.workoutplanday")),
                ("workout", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="workout_plans.garminworkout")),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.RunPython(forwards_copy_day_to_items, backwards_copy_items_to_day),
        migrations.RemoveField(model_name="workoutplanday", name="workout"),
        migrations.RemoveField(model_name="workoutplanday", name="cardio_activity"),
        migrations.RemoveField(model_name="workoutplanday", name="completed"),
    ]

