# Generated by Django 5.1.2 on 2026-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plans', '0004_workoutplanitem_multi_per_day'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workoutplanitem',
            constraint=models.UniqueConstraint(fields=('day', 'position'), name='uniq_plan_day_item_position'),
        ),
    ]
